import { ApiData } from '@/@types/Api'
import axios from 'axios'
import Head from 'next/head'
import Image from 'next/image'

interface Props {
  res: string
}

export default function Home(props: Props) {
  const characters: ApiData = JSON.parse(props.res)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {characters.results.map((character) => (
          <div key={character.id}>
            <Image
              loader={() => character.image}
              src={character.image}
              width={300}
              height={300}
              alt="character"
            />
            <p>{character.name}</p>
          </div>
        ))}
      </main>
    </>
  )
}

export async function getStaticProps() {
  const res = await axios
    .get<ApiData>('https://rickandmortyapi.com/api/character')
    .then(({ data }) => {
      return JSON.stringify(data)
    })

  return {
    props: {
      res,
    },
  }
}
